#!/bin/sh
echo "Running Linters:"

# Run tslint and get the output and return code
tslint=$(npm run lint)
ret_code=$?

# If it didn't pass, announce it failed and print the output
if [ $ret_code != 0 ]; then
	printf "TSlint FAILED: Commit contains files with TSlint errors !!!"
	echo "$tslint\n"
	exit 1
else
	printf "TSlint SUCCESS: Commit allowed."
	exit 0
fi
