#!/bin/sh
pass=true
NC='\033[0m'
RED='\033[1;31m'
GREEN='\033[0;32m'

echo "Running Linters:"

# Run tslint and get the output and return code
tslint=$(npm run lint)
ret_code=$?

# If it didn't pass, announce it failed and print the output
if [ $ret_code != 0 ]; then
	printf "\n${RED}tslint failed:${NC}"
	echo "$tslint\n"
	pass=false
else
	printf "${GREEN}tslint passed.${NC}\n"
fi
